# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redisk}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Quint"]
  s.date = %q{2010-08-15}
  s.description = %q{Redisk includes Redisk::IO which is ~ Ruby's stdlib IO. It can be used with stdlib's Logger to log directly to redis}
  s.email = %q{aaron@quirkey.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "HISTORY",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "examples/rails.rb",
     "examples/yajl.rb",
     "lib/redisk.rb",
     "lib/redisk/helper.rb",
     "lib/redisk/io.rb",
     "lib/redisk/logger.rb",
     "lib/redisk/stat.rb",
     "redisk.gemspec",
     "spec/fixtures/rails.log",
     "spec/redis-test.conf",
     "spec/redisk_io_spec.rb",
     "spec/redisk_logger_spec.rb",
     "spec/redisk_stat_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/quirkey/redis_log}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An interface to Redis that mimic's Ruby's IO classes}
  s.test_files = [
    "spec/redisk_io_spec.rb",
     "spec/redisk_logger_spec.rb",
     "spec/redisk_stat_spec.rb",
     "spec/spec_helper.rb",
     "examples/rails.rb",
     "examples/yajl.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, [">= 0.1.1"])
      s.add_runtime_dependency(%q<redis-namespace>, [">= 0.1.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<redis>, [">= 0.1.1"])
      s.add_dependency(%q<redis-namespace>, [">= 0.1.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<redis>, [">= 0.1.1"])
    s.add_dependency(%q<redis-namespace>, [">= 0.1.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

